### ISSUE TITLE
Treated Wood Microblocks Have Broken Textures

### ISSUE THREAD

**Issue by EmosewaPixel** [BetterWithMods/BetterWithEngineering#8]
Due to the changes to microblocks in the latest BWM version, the Treated Wood microblocks have broken textures now.
![image](https://user-images.githubusercontent.com/25333164/38171899-ce466f64-35a2-11e8-9f8c-30d005f473b8.png)

**Comment by primetoxinz** [comment]
Fixed in 1.5
